/*
 * WebRatio number separators map
 * Used to convert moment.js number separators to the corrent ones
 */

module.exports = {
    "sq": {"decimal": ",", "group": " "},
    "sq-AL": {"decimal": ",", "group": " "},
    "ar": {"decimal": ".", "group": ","},
    "ar-DZ": {"decimal": ".", "group": "."},
    "ar-BH": {"decimal": ".", "group": ","},
    "ar-EG": {"decimal": ".", "group": ","},
    "ar-IQ": {"decimal": ".", "group": ","},
    "ar-JO": {"decimal": ".", "group": ","},
    "ar-KW": {"decimal": ".", "group": ","},
    "ar-LB": {"decimal": ",", "group": "."},
    "ar-LY": {"decimal": ",", "group": "."},
    "ar-MA": {"decimal": ",", "group": "."},
    "ar-OM": {"decimal": ".", "group": ","},
    "ar-QA": {"decimal": ".", "group": ","},
    "ar-SA": {"decimal": ".", "group": ","},
    "ar-SD": {"decimal": ".", "group": ","},
    "ar-SY": {"decimal": ".", "group": ","},
    "ar-TN": {"decimal": ",", "group": " "},
    "ar-AE": {"decimal": ".", "group": ","},
    "ar-YE": {"decimal": ".", "group": ","},
    "be": {"decimal": ",", "group": " "},
    "be-BY": {"decimal": ",", "group": " "},
    "bg": {"decimal": ",", "group": " "},
    "bg-BG": {"decimal": ",", "group": " "},
    "ca": {"decimal": ",", "group": "."},
    "ca-ES": {"decimal": ",", "group": "."},
    "zh": {"decimal": ".", "group": ","},
    "zh-CN": {"decimal": ".", "group": " "},
    "zh-HK": {"decimal": ".", "group": " "},
    "zh-SG": {"decimal": ".", "group": " "},
    "zh-TW": {"decimal": ".", "group": " "},
    "hr": {"decimal": ",", "group": "."},
    "hr-HR": {"decimal": ",", "group": "."},
    "cs": {"decimal": ",", "group": " "},
    "cs-CZ": {"decimal": ",", "group": " "},
    "da": {"decimal": ",", "group": "."},
    "da-DK": {"decimal": ",", "group": "."},
    "nl": {"decimal": ",", "group": "."},
    "nl-BE": {"decimal": ",", "group": "."},
    "nl-NL": {"decimal": ",", "group": "."},
    "en": {"decimal": ".", "group": ","},
    "en-AU": {"decimal": ".", "group": ","},
    "en-CA": {"decimal": ".", "group": ","},
    "en-GB": {"decimal": ".", "group": ","},
    "en-IN": {"decimal": ".", "group": ","},
    "en-IE": {"decimal": ".", "group": ","},
    "en-MT": {"decimal": ".", "group": ","},
    "en-PH": {"decimal": ".", "group": ","},
    "en-SG": {"decimal": ".", "group": ","},
    "en-US": {"decimal": ".", "group": ","},
    "en-ZA": {"decimal": ".", "group": " "},
    "et": {"decimal": ",", "group": " "},
    "et-EE": {"decimal": ",", "group": " "},
    "fi": {"decimal": ",", "group": " "},
    "fi-FI": {"decimal": ",", "group": " "},
    "fr": {"decimal": ",", "group": " "},
    "fr-BE": {"decimal": ",", "group": "."},
    "fr-CA": {"decimal": ",", "group": " "},
    "fr-FR": {"decimal": ",", "group": " "},
    "fr-LU": {"decimal": ",", "group": "."},
    "fr-CH": {"decimal": ".", "group": " "},
    "de": {"decimal": ",", "group": "."},
    "de-AT": {"decimal": ",", "group": "."},
    "de-DE": {"decimal": ",", "group": "."},
    "de-CH": {"decimal": ".", "group": " "},
    "de-LU": {"decimal": ",", "group": "."},
    "el": {"decimal": ",", "group": "."},
    "el-CY": {"decimal": ",", "group": "."},
    "el-GR": {"decimal": ",", "group": "."},
    "iw": {"decimal": ".", "group": ","},
    "iw-IL": {"decimal": ".", "group": ","},
    "hi": {"decimal": ".", "group": ","},
    "hi-IN": {"decimal": ".", "group": ","},
    "hu": {"decimal": ",", "group": " "},
    "hu-HU": {"decimal": ",", "group": " "},
    "is": {"decimal": ",", "group": "."},
    "is-IS": {"decimal": ",", "group": "."},
    "in": {"decimal": ",", "group": "."},
    "in-ID": {"decimal": ",", "group": "."},
    "ga": {"decimal": ".", "group": ","},
    "ga-IE": {"decimal": ".", "group": ","},
    "it": {"decimal": ",", "group": "."},
    "it-IT": {"decimal": ",", "group": "."},
    "it-CH": {"decimal": ".", "group": " "},
    "ja": {"decimal": ".", "group": ","},
    "ja-JP": {"decimal": ".", "group": ","},
    "ko": {"decimal": ".", "group": ","},
    "ko-KR": {"decimal": ".", "group": ","},
    "lv": {"decimal": ",", "group": " "},
    "lv-LV": {"decimal": ",", "group": " "},
    "lt": {"decimal": ",", "group": " "},
    "lt-LT": {"decimal": ",", "group": " "},
    "mk": {"decimal": ",", "group": "."},
    "mk-MK": {"decimal": ",", "group": "."},
    "ms": {"decimal": ".", "group": ","},
    "ms-MY": {"decimal": ".", "group": ","},
    "mt": {"decimal": ".", "group": ","},
    "mt-MT": {"decimal": ".", "group": ","},
    "no": {"decimal": ",", "group": " "},
    "no-NO": {"decimal": ",", "group": " "},
    "pl": {"decimal": ",", "group": " "},
    "pl-PL": {"decimal": ",", "group": " "},
    "pt": {"decimal": ",", "group": "."},
    "pt-BR": {"decimal": ",", "group": "."},
    "pt-PT": {"decimal": ",", "group": "."},
    "ro": {"decimal": ",", "group": "."},
    "ro-RO": {"decimal": ",", "group": "."},
    "ru": {"decimal": ",", "group": " "},
    "ru-RU": {"decimal": ",", "group": " "},
    "sr": {"decimal": ",", "group": "."},
    "sr-BA": {"decimal": ",", "group": "."},
    "sr-ME": {"decimal": ",", "group": "."},
    "sr-RS": {"decimal": ",", "group": "."},
    "sr-CS": {"decimal": ",", "group": "."},
    "sk": {"decimal": ",", "group": " "},
    "sk-SK": {"decimal": ",", "group": " "},
    "sl": {"decimal": ",", "group": " "},
    "sl-SI": {"decimal": ",", "group": " "},
    "es": {"decimal": ",", "group": "."},
    "es-AR": {"decimal": ",", "group": "."},
    "es-BO": {"decimal": ",", "group": "."},
    "es-CL": {"decimal": ",", "group": "."},
    "es-CO": {"decimal": ",", "group": "."},
    "es-CR": {"decimal": ",", "group": "."},
    "es-DO": {"decimal": ".", "group": ","},
    "es-EC": {"decimal": ",", "group": "."},
    "es-SV": {"decimal": ".", "group": ","},
    "es-GT": {"decimal": ".", "group": ","},
    "es-HN": {"decimal": ".", "group": ","},
    "es-MX": {"decimal": ".", "group": ","},
    "es-NI": {"decimal": ".", "group": ","},
    "es-PA": {"decimal": ".", "group": ","},
    "es-PY": {"decimal": ",", "group": "."},
    "es-PE": {"decimal": ".", "group": ","},
    "es-PR": {"decimal": ".", "group": ","},
    "es-ES": {"decimal": ",", "group": "."},
    "es-US": {"decimal": ".", "group": ","},
    "es-UY": {"decimal": ",", "group": "."},
    "es-VE": {"decimal": ",", "group": "."},
    "sv": {"decimal": ",", "group": " "},
    "sv-SE": {"decimal": ",", "group": " "},
    "th": {"decimal": ".", "group": ","},
    "th-TH": {"decimal": ".", "group": ","},
    "tr": {"decimal": ",", "group": "."},
    "tr-TR": {"decimal": ",", "group": "."},
    "uk": {"decimal": ",", "group": " "},
    "uk-UA": {"decimal": ",", "group": " "},
    "vi": {"decimal": ",", "group": "."},
    "vi-VN": {"decimal": ",", "group": "."}
};
